apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  namespace: rss
  labels:
    app: rss-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-site
  template:
    metadata:
      labels:
        app: rss-site
    spec:
      containers:
      - name: rss-site
        image: localhost:5000/rss-site:latest
        imagePullPolicy: Always
        command: ["npm"]
        args:
          - start
        env: 
          - name: HOST
            value: https://rss.mchone.dev
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: rss-secrets
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: rss-secrets
                key: CLIENT_SECRET
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rss-secrets
                key: DATABASE_URL
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: rss-secrets
                key: SESSION_SECRET
