apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  namespace: rss
  labels:
    app: rss-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-site
  template:
    metadata:
      labels:
        app: rss-site
    spec:
      containers:
      - name: rss-site
        image: localhost:5000/rss-site:latest
        imagePullPolicy: Always
        command: ["npm"]
        args:
          - start
        envFrom:
          - secretRef:
            name: rss-secrets
